version: "3"
services:
  npk-frontend-system:
    container_name: npk-frontend-system
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.256'
          memory: 512M
        reservations:
          cpus: '0.128'
          memory: 128M
    image: topsan-profile
    restart: always
    ports:
      - 88:80
   
     
   